name: Chequeo de licencias en proyectos Java con Gradle

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      
      - name: License check
        run: ./gradlew licenseFormatCheck
      
      - name: License report
        run: ./gradlew licenseFormatReport


